### ISSUE TITLE
[Hw-Wallet-Js] JS interface for hardware wallet

### ISSUE THREAD

**Issue by gz-c** [skycoin/hardware-wallet-js#1]
Need a JS interface library for the Skycoin hardware wallet.  Other hardware wallets such as Nano Ledger do this, which can be used as a reference.  I assume this requires the nodejs usbhid module.  
The library should have a reasonable API for the basic operations of address generation and signing.

Once this library is developed, the skycoin wallet frontend team will integrate it into the desktop wallet

**Comment by mpsido** [comment]
Here are the existing functions in the golang public API:
* DeviceCheckMessageSignature
* MessageButtonAck
* DeviceSetMnemonic
* DecodeFailMsg
* DecodeResponseSkycoinAddress
* DecodeResponseSkycoinSignMessage
* DeviceAddressGen
* DeviceSignMessage
* DeviceConnected
* WipeDevice
* DeviceChangePin
* DevicePinMatrixAck

The should have their equivalent in the javascript code
