### ISSUE TITLE
Problem when signing a transaction with 8 inputs

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-js#102]
**Describe the bug**
When a transaction with 8 inputs is signed, the last signature is invalid, it has `\u0000` added at the end.

**Environment information:**

- OS: e.g. Windows
- Platform: x86
- Firmware Version: ab2e80c

**Steps to Reproduce**
Call the `devSkycoinTransactionSign` function with 8 inputs. It does not matter if the inputs are the same or not.

**Actual behavior**
The last signature returned by `devSkycoinTransactionSign` is invalid, as it has `\u0000` at the end. Also, the console shows `Wire format is invalid { ProtocolError: missing required 'padding'` before the signaturas list.
![cmd](https://user-images.githubusercontent.com/34079003/56082345-e311cf80-5de5-11e9-9de5-b4006487d8bc.png)

**Expected behavior**
When a transaction with 8 inputs is signed, 8 valid signatures should be received.

**Additional context**
The problem is not present in the hardware wallet daemon

**Possible implementation**

**Comment by olemis** [comment]
> The problem is not present in the hardware wallet daemon

@Senyoret1 @stdevMac maybe the quick solution will be to document that hw-js library only supports `7` {in,out}puts , and move forward with skycoin/hardware-wallet#79

**Comment by Senyoret1** [comment]
That would work well as a temporary solution. I clould add the limit to the front-end.

**Comment by olemis** [comment]
@stdevMac just modify README
