### ISSUE TITLE
[Hw-Wallet-Js] Api to create and load seeds

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-js#11]
In wallet.trezor.io, when connecting a new wallet it is possible to configure it with a new seed or recovering a previous seed. When creating a new seed, apparently the seed is created by the hardware wallet itself and therefore it is necessary to make a backup immediately afterwards, this would mean that the pc could not know the seed at any time. When recovering a previous seed, it is necessary to introduce the words in random order, so the pc could not know exactly what the seed is, just the separated words.

To implement similar functionalities, the api js includes the `devSetMnemonic` function, but this function implies that the pc knows the seed, which could be a security risk. To maintain a higher level of security, it may be necessary to create additional functions.

**Comment by mpsido** [comment]
related to issue https://github.com/skycoin/hardware-wallet/issues/13

**Comment by mpsido** [comment]
Related to https://github.com/skycoin/hardware-wallet/issues/16 (method to check if the mnemonic is set using address generation message)
