### ISSUE TITLE
Automate hw-js release process in Travis 

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet-js#112]
**Feature description**

Automate release process steps in Travis script

**Describe the solution you'd like**
Add `deploy` sections in `.travis.yml` script

**Describe alternatives you've considered**
Manual release is not an option

**Additional context**
see skycoin/hardware-wallet#183 as a reference

**Possible implementation**

- [x] Add `make release` target
- [x] Add deploy step for Travis jobs
- [x] Invoke `make release` when Travis build has been triggered by a git tag.
- [x] Release matrix build for ~`osx` and~ `linux`
- [x] Ensure README is in sync with release script
- [x] Explain use of `beta` version
- [x] Deploy to Github releases
- [ ] Pre-release testing steps
- [x] Deploy to `npm`

**Comment by stdevStark** [comment]
@olemis please see [npm beta release](https://www.npmjs.com/package/skywallet/v/1.0.0-beta.0) .
