### ISSUE TITLE
[Hw-Wallet-Js]: Procedure to restore the seeds

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-js#18]
Currently the only way to restore the seeds is to introduce them manually and then call `devSetMnemonic`. However, restoring the seeds in that way is insecure (that's just why `devGenerateMnemonic` was created). It is necessary to create a safer procedure, probably like the one used by Trezor.

**Comment by mpsido** [comment]
Related to : https://github.com/skycoin/hardware-wallet/issues/33
