### ISSUE TITLE
[Hw-Wallet-Js]: Function to know if it is necessary to backup the seed

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-js#20]
Because it is only possible to backup the seed once, the UI of the applications that use this library should show the option for making a backup only if it has not yet been done (if the screen of the hardware wallet shows the “NEEDS BACKUP!” message). To make this possible it is necessary to add an API endpoint for consulting if it is necessary to backup the seed or not.

**Comment by mpsido** [comment]
See https://github.com/skycoin/hardware-wallet/issues/31
