### ISSUE TITLE
Expect to receive the pin asynchronously

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-js#23]
In https://github.com/skycoin/hardware-wallet-js/commit/4cc17d32ff979ef6b16e859d132879ca8a78d830 a new requirement was added on the functions of the library that may require the user to enter the pin: a function that returns the pin entered by the user. However, the code expects the function to return a valid pin synchronously, which has two problems.

The first problem is that in the created example `scanf` is used to obtain the user's pin, which works correctly in console apps, since blocking the execution of the program does not represent any problem. However, in the software wallet the pin will be obtained through several controls running inside Angular, which means that the pin would be obtained asynchronously after the user finishes interacting with the UI. In general, JavaScript is a language that runs on a single processor thread, so blocking the execution until the function returns the pin would imply blocking the Electron app.

The second problem is that the approach does not consider that the user could cancel the operation. In wallet.trezor.io, when the user is asked for the pin, the user can simply close the modal window and the hardware wallet screen stops showing the pin matrix. In the Skycoin software wallet something similar should happen. If it is not possible at this moment to cancel the operation in the hardware wallet and stop showing the pin matrix, at least it should be canceled in the library and the user could disconnect and reconnect the hardware wallet in case he wants to perform another operation.

Probably a solution to this would be to make the library not request a function that returns the pin synchronously, but a function that returns a promise with the pin. That would allow several things: when calling the function the UI would know that it is necessary to show the popup asking the user to introduce pin, returning a promise would avoid having to block the Electron app and the promise could fail, indicating that the user decided not to introduce the pin.

**Comment by mpsido** [comment]
Continuation of issue: #19
