### ISSUE TITLE
[Hw-Wallet-Js]: Verify the address on the hardware wallet screen

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-js#24]
As a security measure, when adding an address in wallet.trezor.io it is necessary to confirm the address on the hardware wallet screen before being able to see the full address in the software wallet. It would be good if this library includes a function that allows to see the address on the screen of the hardware wallet and asks the user to confirm that the address is the same as the one shown in the software wallet, as it is done in Trezor.

**Comment by mpsido** [comment]
This feature requires updating the firmware code: creating issue: https://github.com/skycoin/hardware-wallet/issues/30

**Comment by mpsido** [comment]
@Senyoret1 see question in issue https://github.com/skycoin/hardware-wallet/issues/30
