### ISSUE TITLE
[Hw-Wallet-Js]: Function to know if the hardware wallet have a PIN

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-js#26]
When `devChangePin` is called the user could be asked for the PIN 2 times (if the hardware wallet does not have a PIN) or 3 times (if the hardware wallet does have a PIN). Since the library does not send information about why it is requesting the PIN, it is not possible to give clear explanations to the user in the UI about why it is being requested so many times. With a function that lets know if the hardware wallet has a PIN or not, it World be posible to know in advance how many times the user will be asked for the PIN and show appropriate messages in the UI.

Additionally, the function would be useful to show a warning message reminding the user that he should assign a PIN to the hardware wallet.

**Comment by mpsido** [comment]
See: https://github.com/skycoin/hardware-wallet/issues/31
