### ISSUE TITLE
[Hw-Wallet-Js]: It is not possible to connect if using the new firmware

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-js#27]
Due to the fact that in the most recent versions of the firmware the name of the device was updated, the library does not longer recognizes the hardware wallet. When calling functions, the `Device not connected` error is returned.

The error may be due to the name checking done in this part of the code, but I really do not know if there are similar checks in other parts of the code that could also cause problems:
https://github.com/skycoin/hardware-wallet-js/blob/d0ef76e2355ebef7503e72c05d81c56163df4345/device-wallet.js#L25-L35

**Comment by mpsido** [comment]
For now just manually change "SatoshiLabs" for "SkycoinFoundation". 
I want to send this fix after I finished with this issue : https://github.com/skycoin/hardware-wallet/issues/2

**Comment by mpsido** [comment]
@Senyoret1  Don't forget to update your udev rules:

```
## 0483:df11 STMicroelectronics STM Device in DFU Mode
SUBSYSTEM=="usb", ATTR{idVendor}=="0483", ATTR{idProduct}=="df11", MODE="0666"
## 0483:3748 STMicroelectronics ST-LINK/V2
SUBSYSTEM=="usb", ATTR{idVendor}=="0483", ATTR{idProduct}=="3748", MODE="0666"
## 0483:374b STMicroelectronics ST-LINK/V2.1 (Nucleo-F103RB)
SUBSYSTEM=="usb", ATTR{idVendor}=="0483", ATTR{idProduct}=="374b", MODE="0666"
## 313a:0001
SUBSYSTEM=="usb", ATTR{idVendor}=="313a", ATTR{idProduct}=="0001", MODE="0666"
KERNEL=="hidraw*", ATTRS{idVendor}=="313a", ATTRS{idProduct}=="0001", MODE="0666"
```

```bash
sudo cp 99-skycoin-dev-kit.rules /etc/udev/rules.d/
sudo udevadm control --reload-rules
sudo udevadm trigger
```

See also here: [configure-your-usb-module](https://github.com/skycoin/hardware-wallet/blob/master/tiny-firmware/README.md#configure-your-usb-module)
