### ISSUE TITLE
[Hw-Wallet-Js]: the word list is not enforced while restoring a seed

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-js#31]
I'm not sure if this issue goes in this repository, but when restoring a seed with `devRecoveryDevice` the word list is not being enforced, although this part of the code appears to be requesting it to be enforced:
https://github.com/skycoin/hardware-wallet-js/blob/c182f5954e83489b00bc5f0a51a9a3608c306597/device-wallet.js#L324-L338

**Comment by mpsido** [comment]
Enforce word list in the code means that they want every word of the list to be in the bip39 dictionnary.

I don't understand what is expected from this issue

**Comment by mpsido** [comment]
Thank you @Senyoret1 it was just a typo in my code enforceWordList -> enforceWordlist, it is fixed
