### ISSUE TITLE
[Hw-Wallet-Js]: Repetitive code 

### ISSUE THREAD

**Issue by mpsido** [skycoin/hardware-wallet-js#33]
A lot of the code in device-wallet.js respects a repeated pattern.

In order to keep code small and make future developments easier it is time considering using a macro language like [sweet.js](https://www.sweetjs.org/) or [any other](https://stackoverflow.com/questions/29421437/real-macros-on-javascript-node-js).

**Comment by gz-c** [comment]
leave this for senyoret to do later
