### ISSUE TITLE
Implement message IsMemoryProtected in hw JS API

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet-js#44]
**Feature description**

Implement memory protect message in JS API

**Is your feature request related to a problem? Please describe.**
Not possible to determine from JS if Skywallet device is memory protected .

**Describe the solution you'd like**

**Additional context**
See skycoin/hardware-wallet#45 and the patch in skycoin/hardware-wallet#60 .

**Possible implementation**

- [ ] New command `deviceIsMemoryProtected` similar to skycoin/hardware-wallet-go#18 .
- [ ] Test cases working against emulator (determine if it makes sense)

**Comment by jdknives** [comment]
I think this needs to be assigned to @Senyoret1 rather than stdevs as he is doing the work on JS.

**Comment by Senyoret1** [comment]
I am not familiar with how the JS code uses protobuf to connect directly to the hardware wallet, as that part was not developed by me. If necessary, I could take a look at it, but someone working directly with the C code and with protobuf should be able to do it much faster than me.

**Comment by olemis** [comment]
> I think this needs to be assigned to @Senyoret1 rather than stdevs as he is doing the work on JS.

@jdknives as I was hoping you knew already @Senyoret1 is not working on hw-js library . He has the final word on some decisions though since he is the one consuming the API .

**Comment by olemis** [comment]
> If necessary, I could take a look at it,

@Senyoret1 it's fine , @stdevIvr will take a look into this eventually .

@gz-c we have deferred this issue until the last time since we are short of devices and programmers for testing and this feature is potentially risky . That's why it's already marked as `todo`.

**Comment by Senyoret1** [comment]
@olemis I think this is not needed for V1. The desktop wallet does not check if the device has memory protection and, at least until now, I do not think it's necessary. What is really important is to show an graphical indication on the device itself.

**Comment by olemis** [comment]
> @olemis I think this is not needed for V1.

well, this changed a little bit and now is part of `GetFeatures` hence needed for v1
