### ISSUE TITLE
Run all tests with the npm test rule(`npm test`)

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet-js#50]
**Feature description**
When you type `npm test` [all tests](https://github.com/skycoin/hardware-wallet-js/tree/master/test) should run.

All tests should run as part of the CI process, an alternative could be fix the [packages.json](https://github.com/skycoin/hardware-wallet-js/blob/21a9941e9a65d322a6795106c22cfc8553d95b09/package.json#L10) and run only some specific tests in travis with node directly.

**Additional context**
Related to https://github.com/skycoin/hardware-wallet-js/issues/38

**Possible implementation**
Make this working is not so trivial, as this have integration tests that run against the device(physical or emulated), so this can be considered related to https://github.com/skycoin/hardware-wallet/issues/28

**Logs:**
```.bash
hardware-wallet-js (master)
└─ $ ▶  npm test

> hardware-wallet-js@1.0.0 test /hardware-wallet-js
> node test/*.js

    Device wallet buffer creation    
pass 1 - Fail message (3ms)
pass 2 - Success message (2ms)
pass 3 - SkycoinAddress message (1ms)
pass 4 - ResponseSkycoinAddress message (1ms)

Total: 4
Passed: 4 100%

(node:5222) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

[This test](https://github.com/skycoin/hardware-wallet-js/blob/21a9941e9a65d322a6795106c22cfc8553d95b09/test/transaction-test.js#L536) was not run

**Comment by olemis** [comment]
This one will be fixed as a side-effect of #71
