### ISSUE TITLE
Set user host device entropy to the hardware-wallet to be combined with internal hw entropy

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet-js#65]
**Feature description**
Combine internal hw device entropy with the host one.

**Is your feature request related to a problem? Please describe.**
Related to skycoin/hardware-wallet#88

**Describe the solution you'd like**
Send entropy to the device before call `GenerateMnemonic`

**Describe alternatives you've considered**
Other alternative could be request entropy from the device, but as the protocol implementation is not working with a call/call_back scheme this can make ugly the implementation.

**Comment by olemis** [comment]
@stdevAlDen should use `randombytes` instead of `secure-random` .
