### ISSUE TITLE
Inconsistency in protocol messages definition

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet-js#67]
**Describe the bug**
Protobuf file definitions should be exactly equal between projects

**Environment information:**

- Any

**Steps to Reproduce**
Make a diff between:

- [messages.options](https://github.com/skycoin/hardware-wallet-js/blob/6157b369ad2a8b40fd8f75f546adc4f2a38f95bb/protob/messages.options) vs [messages.options)](https://github.com/skycoin/hardware-wallet/blob/230a1d5b76fb210506adc257b619bdd6201e5135/tiny-firmware/protob/messages.options)

- [messages.proto](https://github.com/skycoin/hardware-wallet-js/blob/6157b369ad2a8b40fd8f75f546adc4f2a38f95bb/protob/messages.proto) vs [messages.proto)](https://github.com/skycoin/hardware-wallet/blob/230a1d5b76fb210506adc257b619bdd6201e5135/tiny-firmware/protob/messages.proto)

- [types.options](https://github.com/skycoin/hardware-wallet-js/blob/6157b369ad2a8b40fd8f75f546adc4f2a38f95bb/protob/types.options) vs [types.options)](https://github.com/skycoin/hardware-wallet/blob/230a1d5b76fb210506adc257b619bdd6201e5135/tiny-firmware/protob/types.options)

- [types.proto](https://github.com/skycoin/hardware-wallet-js/blob/6157b369ad2a8b40fd8f75f546adc4f2a38f95bb/protob/types.proto) vs [types.proto)](https://github.com/skycoin/hardware-wallet/blob/230a1d5b76fb210506adc257b619bdd6201e5135/tiny-firmware/protob/types.proto)

**Actual behavior**
Some messages are failing.

**Expected behavior**
Messages should work ok.

**Possible implementation**
Move all the protouf file to a separate repository and use it as a git submodule any where it is required. Maintain the same file in different projects is error prone.

**Comment by olemis** [comment]
Working on this . See skycoin/harsware-wallet-protob#1

**Comment by stdevAlDen** [comment]
> Working on this . See [skycoin/hardware-wallet-protob#1](https://github.com/skycoin/hardware-wallet-protob/issues/1)

**Comment by olemis** [comment]
@stdevAlDen generation of protobuffer go classes completed in skycoin/hardware-wallet-protob#3 . Please consider adding it as a submodule for building them into this project . By doing so all projects will reuse the same definitions .
