### ISSUE TITLE
Extra characters at the end of the last addess when requesting 12 addresses

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-js#73]
**Describe the bug**
When requesting 12 addresses using the sample seed of the JS library (cloud flower upset remain green metal below cup stem infant art thank) the las address returned by the library is `ouE9prS4XMhVwQa5gwW4hQuiAGam\u0000\u0000\u0000\u0000\u0000\u0000`

A similar error happens when requesting the 50 first addresses.

This does not happens using the Go cli, so the problem must be on this library.

**Environment information:**

- OS: Windows 10
- Platform: Windows 10 pro x64
- Firmware Version: not sure

**Steps to Reproduce**
Call `deviceWallet.devAddressGen(12, 0, false, pinCodeReader, wordReader);` and see the response.

**Actual behavior**
The last address has some extra `\u0000` at the end.

**Expected behavior**
The address should not have extra characters.

**Additional context**
May be this is not too important as the hardware wallets will be limited to one address, at least for some time, and this library should be replaced with the daemon, but could be important in the future.

**Possible implementation**
Some time ago there was a similar problem with the function for signing transactions, but I'm not sure if the cause was the same. I think it was solved with https://github.com/skycoin/hardware-wallet-js/pull/35/commits/dc65883ee6ce115b4e9af5e24a1946660a794063

**Comment by olemis** [comment]
this is caused by js `protob` code
