### ISSUE TITLE
Duplicated npm command

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-js#94]
The `Package.json` file has two scripts (`lint` and `format`)  that do exactly the same:

https://github.com/skycoin/hardware-wallet-js/blob/ff7c8e1fe348fc6099c845161ae8ca6e2dc864e7/package.json#L7-L8

@stdevAlDen , was this done for some reason in particular or should it be changed/deleted?

**Comment by stdevAlDen** [comment]
@Senyoret1 & @stdevStark it's just a mistake, `format` command should receive the `--fix` flag.
