### ISSUE TITLE
Integration test cases to catch pre-v1 firmware errors

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet-js#97]
**Feature description**

Firmware changes in skycoin/hardware-wallet#151 need integration tests .

- [x] If the `ApplySettings` message is called with `usePassphrase` set to `null`, the response is that the operation finished correctly, but in fact nothing happens.
- [x] Implement `remove` in `devChangePin` command .
- [x] Set empty label

**Comment by olemis** [comment]
@stdevStark need you to take a look into this , pls

**Comment by stdevIvr** [comment]
@olemis The behavior of the `ApplySettings` function in the firmware, doesn't accepts empty labels. This is a portion of the code:
```C++
        msg->has_label = msg->has_label && strlen(msg->label);
	msg->has_language = msg->has_language && strlen(msg->language);
	if (msg->has_label) {
		layoutDialogSwipe(&bmp_icon_question, _("Cancel"), _("Confirm"), NULL, _("Do you really want to"), _("change name to"), msg->label, "?", NULL, NULL);
		CHECK_BUTTON_PROTECT
	}
```
Look that is "validated" with `strlen(msg->label)`. It must be changed to get that feature.

**Comment by olemis** [comment]
> @olemis The behavior of the `ApplySettings` function in the firmware, doesn't accepts empty labels.

Label may not be empty .
